namespace Jaket.Content;

/// <summary> All entity types. Will replenish over time. </summary>
public enum EntityType
{
    Filth = 0,
    Stray,
    Schism,
    Soldier,
    TheCorpseOfKingMinos,
    Stalker,
    Insurrectionist,
    Ferryman,
    Swordsmachine,
    Drone,
    Streetcleaner,
    V2,
    Mindflayer,
    V2_GreenArm,
    Sentry,
    MaliciousFace,
    Cerberus,
    HideousMass,
    Idol,
    Gabriel,
    Virtue,
    Gabriel_Angry,
    SomethingWicked,
    CancerousRodent,
    VeryCancerousRodent,
    Mandalore,
    FleshPrison,
    FleshPrison_Eye,
    FleshPanopticon,
    FleshPanopticon_Eye,
    FleshPanopticon_Face,
    MinosPrime,
    SisyphusPrime,
    Hand,
    Leviathan,

    AppleBait = 35,
    SkullBait,
    BlueSkull,
    RedSkull,
    Soap,
    Torch,
    Florp,

    Jacob = 42,
    Mako,
    Jake,
    Dalia,
    Jericho,
    Meganeko,
    Tucker,
    BigRock,
    Dawg,
    Sam,
    Cameron,
    Gianni,
    Salad,
    Mandy,
    Joy,
    Weyte,
    Heckteck,
    Hakita,
    Lenval,
    CabalCrow,
    Quetzal,
    John,
    PITR,
    BJ,
    Francis,
    Vvizard,
    Lucas,
    Scott,
    KGC,
    V1,

    Player = 72
}
