namespace Jaket.Content;

/// <summary> All entity types. Will replenish over time. </summary>
public enum EntityType
{
    Filth,
    Stray,
    Schism,
    Soldier,
    TheCorpseOfKingMinos,
    Stalker,
    Insurrectionist,
    Ferryman,
    Swordsmachine,
    Drone,
    Streetcleaner,
    V2,
    Mindflayer,
    V2_GreenArm,
    Sentry,
    MaliciousFace,
    Cerberus,
    HideousMass,
    Idol,
    Gabriel,
    Virtue,
    Gabriel_Angry,
    SomethingWicked,
    CancerousRodent,
    VeryCancerousRodent,
    Mandalore,
    FleshPrison,
    FleshPrison_Eye,
    FleshPanopticon,
    FleshPanopticon_Eye,
    FleshPanopticon_Face,
    MinosPrime,
    SisyphusPrime,
    Hand = 33,
    Leviathan = 34,
    Player = 35
}