namespace Jaket.Content;

/// <summary> All entity types. Will replenish over time. </summary>
public enum EntityType
{
    None = -1,
    Player,

    Filth,
    Stray,
    Schism,
    Soldier,
    TheCorpseOfKingMinos,
    Stalker,
    Insurrectionist,
    Ferryman,
    Swordsmachine,
    Drone,
    Streetcleaner,
    Mindflayer,
    V2_RedArm,
    V2_GreenArm,
    Sentry,
    Gutterman,
    Guttertank,
    MaliciousFace,
    Cerberus,
    HideousMass,
    Idol,
    Mannequin,
    Minotaur,
    Virtue,
    Gabriel,
    Gabriel_Angry,
    SomethingWicked,
    FleshPrison,
    FleshPrison_Eye,
    FleshPanopticon,
    FleshPanopticon_Eye,
    FleshPanopticon_Face,
    MinosPrime,
    SisyphusPrime,
    CancerousRodent,
    VeryCancerousRodent,
    Mandalore,
    Johninator,
    Puppet,
    Hand,
    Leviathan,
    Minotaur_Chase,
    SecuritySystem_Main,
    SecuritySystem_RocketLauncher, SecuritySystem_RocketLauncher_,
    SecuritySystem_Mortar, SecuritySystem_Mortar_,
    SecuritySystem_Tower, SecuritySystem_Tower_,
    Brain,

    BlueSkull,
    RedSkull,
    Soap,
    Torch,
    Florp,

    AppleBait,
    SkullBait,
    FunnyStupidFish,
    PitrFish,
    TroutFish,
    MetalFish,
    ChomperFish,
    BombFish,
    EyeballFish,
    FrogFish,
    DopeFish,
    StickFish,
    CookedFish,
    Shark,
    BurntStuff,

    Hakita,
    Pitr,
    Victoria,
    Heckteck,
    CabalCrow,
    Lucas,
    Francis,
    Jericho,
    BigRock,
    Mako,
    Samuel,
    Salad,
    Meganeko,
    KGC,
    BJ,
    Jake,
    John,
    Quetzal,
    Gianni,
    Weyte,
    Lenval,
    Joy,
    Mandy,
    Cameron,
    Dalia,
    Tucker,
    Scott,
    Jacob,
    Vvizard,
    V1,
    V2,
    V3,
    xzxADIxzx,
    Sowler,

    Coin,
    Rocket,
    Ball
}
