namespace Jaket.Content;

/// <summary> All entity types. Will replenish over time. </summary>
public enum EntityType : byte
{
    None   = 0xFF,
    Player = 0x00,

    #region items

    SkullBlue,
    SkullRed,
    Soap,
    Torch,
    Moon,
    Florp,
    BaitApple,
    BaitFace,

    FishFunny,
    FishPitr,
    FishTrout,
    FishMetal,
    FishChomper,
    FishBomb,
    FishBall,
    FishFrog,
    FishDope,
    FishStick,
    FishCooked,
    FishShark,
    FishBurnt,

    Hakita,
    Pitr,
    Victoria,
    Heckteck,
    CabalCrow,
    Lucas,
    Zombie,
    Francis,
    Jericho,
    BigRock,
    Mako,
    FlyingDog,
    Samuel,
    Salad,
    Meganeko,
    KGC,
    Benjamin,
    Jake,
    John,
    Lizard,
    Quetzal,
    Gianni,
    Weyte,
    Lenval,
    Joy,
    Mandy,
    Cameron,
    Dalia,
    Tucker,
    Scott,
    Jacob,
    Vvizard,
    V1,
    V2,
    V3,
    xzxADIxzx,
    Sowler,

    #endregion
    #region weapons

    RevolverBlue,
    RevolverBlueAlt,
    RevolverGreen,
    RevolverGreenAlt,
    RevolverRed,
    RevolverRedAlt,

    ShotgunBlue,
    ShotgunBlueAlt,
    ShotgunGreen,
    ShotgunGreenAlt,
    ShotgunRed,
    ShotgunRedAlt,

    NailgunBlue,
    NailgunBlueAlt,
    NailgunGreen,
    NailgunGreenAlt,
    NailgunRed,
    NailgunRedAlt,

    RailgunBlue,
    RailgunGreen,
    RailgunRed,

    RocketlBlue,
    RocketlGreen,
    RocketlRed,

    #endregion
    #region projectiles

    Core,
    SawbladeCommon,
    SawbladeFodder,
    SawbladeHeated,
    Rocket,
    Cannonball,

    #endregion
    #region explosions

    Shockwave,
    Blastwave,
    ShotgunExplosion,
    HammerExplosionWeak,
    HammerExplosionWarm,
    HammerParticleLight,
    HammerParticleMedium,
    HammerParticleHeavy,

    #endregion

    Filth,
    Stray,
    Schism,
    Soldier,
    TheCorpseOfKingMinos,
    Stalker,
    Insurrectionist,
    Ferryman,
    Swordsmachine,
    Drone,
    Streetcleaner,
    Mindflayer,
    V2_RedArm,
    V2_GreenArm,
    Sentry,
    Gutterman,
    Guttertank,
    MaliciousFace,
    Cerberus,
    HideousMass,
    Idol,
    Mannequin,
    Minotaur,
    Virtue,
    Gabriel,
    Gabriel_Angry,
    SomethingWicked,
    FleshPrison,
    FleshPrison_Eye,
    FleshPanopticon,
    FleshPanopticon_Eye,
    FleshPanopticon_Face,
    MinosPrime,
    SisyphusPrime,
    CancerousRodent,
    VeryCancerousRodent,
    Mandalore,
    Johninator,
    Puppet,
    Hand,
    Leviathan,
    Minotaur_Chase,
    SecuritySystem_Main,
    SecuritySystem_RocketLauncher, SecuritySystem_RocketLauncher_,
    SecuritySystem_Mortar, SecuritySystem_Mortar_,
    SecuritySystem_Tower, SecuritySystem_Tower_,
    Brain
}
