# maintainers:
# Nocturne, Doomguy

# notifications
outdated-mod = Deine Version von Jaket ist [red]veraltet[]!\n[16][light]{0} ► {1} /// {2}
unprivileged = Du darfst keine [red]Cheats[] benutzen!\n[16][light]Der Besitzer der Lobby wählt die Personen aus, die mit diesem Privileg gesegnet werden
major-assist = Du darfst keine [red]Assists[] benutzen!\n[16][light]Keine maschinelle Lebensform sollte im Kampf große Assists verwenden, das wäre unfair
load-mission = Du kannst die [red]Mission nicht wechseln[]!\n[16][light]Nur der Besitzer der Lobby besitzt diese Fähigkeit

spray.choose = [red]Du hast noch kein Spray-Bild ausgewählt.\n[16][light]Das kann zweifellos in den Einstellungen gemacht werden :I
spray.toobig = [red]Dieses Bild ist tatsächlich zu groß.\n[16][light]Die maximale Größe ist auf 512 Kilobytes begrenzt :o

lobby.copied = [green]Lobby-Code erfolgreich kopiert!\n[16][light]Teile ihn mit deinen Atzen, damit sie beitreten können :D
lobby.failed = [red]Kein Lobby-Code in der Zwischenablage gefunden.\n[16][light]Stelle sicher, dass er ohne Leerzeichen kopiert wurde :(
lobby.banned = [red]Du wurdest in dieser Lobby gebannt, sadge.\n[16][light]Vielleicht warst du unartig :)
lobby.modded = [red]Du hast inkompatible Mods installiert.\n[16][light]Die Liste der Mods kann im offiziellen GitHub-Repository gefunden und ergänzt werden

player.joined = [green]Spieler {0} ist beigetreten!
player.died = [orange]Spieler {0} ist gestorben.
player.left = [red]Spieler {0} hat die Lobby verlassen.
player.banned = [red]Spieler {0} wurde gebannt!

fish.too-small = [red]Die Pfanne ist zu klein für diesen Fisch :<
fish.fail = [red]Du hast es nicht geschafft, den Fisch zu kochen :<
bait.took = [green]Ein Fisch hat den Köder genommen :D
bait.nope = [red]Dieser Köder hat hier nicht funktioniert :<

game.countdown = Neue Runde beginnt in [orange]{0} Sekunden[]...
game.lone-team = [red]Es gibt nur ein aktives Team, teilt euch auf und startet die Mission neu
game.win = Team [#{1}]{0}[] hat gewonnen!
team.No0 = gelb
team.No1 = rot
team.No2 = grün
team.No3 = blau
team.No4 = pink

# interface
chat.tip = Tippe deine gewünschte Nachricht oder /help, falls du unschlüssig bist
chat.you = Du
chat.you-only = Du tippst...
chat.others = \ und andere
chat.single = \ tippt...
chat.multiple = \ tippen...

lobby-tab.lobby = -- LOBBY --
lobby-tab.create = LOBBY ERSTELLEN
lobby-tab.creating = ERSTELLT...
lobby-tab.close = LOBBY SCHLIESSEN
lobby-tab.leave = LOBBY VERLASSEN
lobby-tab.invite = FREUNDE EINLADEN
lobby-tab.codes = -- VERBINDUNG --
lobby-tab.copy = LOBBY-CODE KOPIEREN
lobby-tab.join = MIT CODE BEITRETEN
lobby-tab.list = ÖFFENTLICHE LOBBIES DURCHSUCHEN
lobby-tab.config = -- EINSTELLUNGEN --
lobby-tab.name = Name der Lobby
lobby-tab.private = PRIVAT
lobby-tab.fr-only = NUR FREUNDE
lobby-tab.public = ÖFFENTLICH
lobby-tab.default = UNBEKANNT
lobby-tab.allow-pvp = PVP ERLAUBEN
lobby-tab.allow-mod = CLIENT-SEITIGE MODS ERLAUBEN
lobby-tab.ppp-name = BOSSLEBENS-FAKTOR:
lobby-tab.ppp-desc = Prozent pro Spieler ist der Bruchteil der Anfangsgesundheit, der für jeden Spieler ab dem zweiten hinzugefügt wird
lobby-tab.heal-bosses = BOSSE NACH TOD HEILEN
lobby-tab.gamemode = SPIELMODI
lobby-tab.cheats = CHEATS VERWALTEN

lobby-list.name = -- LOBBY-BROWSER --
lobby-list.refresh = AKTUALISIEREN
lobby-list.refreshing = AKTUALISIERE
lobby-list.search = SUCHEN

gameconfig.name = -- SPIELMODI --
gameconfig.mods = MODIFIKATIONEN:
gameconfig.slowmo = \  ZEITLUPE
gameconfig.hammer = \  HAMMER-WAHNSINN
gameconfig.bleedy = \  BLUTEND
gameconfig.titles.No0 = KAMPAGNE
gameconfig.titles.No1 = JAGD
gameconfig.titles.No2 = VERSUS
gameconfig.titles.No3 = ARENA
gameconfig.titles.No4 = WETTRÜSTEN
gameconfig.titles.No5 = BEMALE  [24]\nDIE\n[]    WELT
gameconfig.titles.No6 = VER-    [24]\nSTECK-\n[]   SPIEL
gameconfig.titles.No7 = BOSS-STURM
gameconfig.titles.No8 = HARDCORE
gameconfig.briefs.No0 = Das klassische Jaket-Erlebnis ohne Gameplay-Veränderungen, dies ist die Standardauswahl für Spieldurchgänge.{0}
gameconfig.briefs.No1 = Das Ziel des [pink]pinken Teams[] ist es, die Mission zu beenden, während sie von den anderen Teams gejagt werden.{0}
gameconfig.briefs.No2 = Ein tödlicher Wettkampf zwischen allen Teams für den Titel des Siegers, dies ist die beste Auswahl für Duelle.{0}
gameconfig.briefs.No3 = Ähnlich wie der VERSUS-Modus, aber angepasst für massive Kämpfe zwischen mehreren Spielern.{0}
gameconfig.briefs.No4 = Jede Runde bekommen die Teams eine eigene zufällige Waffe, welche durch Mord von anderen Teams übernommen werden können.{0}
gameconfig.briefs.No5 = Zücke deinen Pinsel und bemale die Welt mit deiner Teamfarbe, das Team mit dem größtem bemalten Bereich gewinnt.{0}
gameconfig.briefs.No6 = Die Beute wird zum Jäger - das [pink]pinke Team[] verfolgt die Verstecker, das letzte überlebende Team trägt den Sieg davon.{0}
gameconfig.briefs.No7 = Ein unfassbar Innovativer und [i]absolut origineller[] Spielmodus, bei dem du pausenlos verstärkte Bosse bekämpfst.{0}
gameconfig.briefs.No8 = Die einzige Wahl einer echten Maschine, beweise deine Würde.{0}
gameconfig.totals.pvp = \  Zwingt PvP aktiviert zu sein\n
gameconfig.totals.hps = \  Team-basierte Lebenspunkte limitieren Wiederbelebungen\n
gameconfig.totals.hok = \  Extra-Heilung nach dem Töten eines Gegners\n
gameconfig.totals.nce = \  Entfernt reguläre Gefechte\n
gameconfig.totals.wle = \  Fügt zufällige Gegner-Wellen hinzu\n

privileges.name = -- PRIVILEGIEN --
privileges.lower = UNPRIVILEGIERT:
privileges.upper = PRIVILEGIERT:
privileges.warn = Privilegierte besitzen die Fähigkeit, Cheats zu benutzen und sind nicht wie andere eingeschränkt; daher können und werden sie deine Lobby zum Absturz bringen - sei vorsichtig

player-list.team = -- TEAMS --
player-list.info = Teams werden durch die Farbe deiner Flügel dargestellt, aber das ist hauptsächlich eine Versus‑Mechanik. Falls ihr euch also nicht gegenseitig verletzen wollt, tretet dem selben Team bei
player-list.list = -- SPIELER --
player-list.owner = Das ist der Besitzer der Lobby, dein Leben hängt von ihm ab :D
player-list.clear = BANLISTE LEEREN

settings.general = -- ALLGEMEIN --
settings.default = STANDARD
settings.green = GRÜN
settings.vanilla = VANILLA
settings.chatloc = CHAT-POSITION
settings.skipmsg = WILLKOMMENS-NACHRICHT ÜBERSPRINGEN
settings.sprays = SPRAYS KONFIGURIEREN
settings.controls = -- STEUERUNG --
settings.reset = ZURÜCKSETZEN

spray.name = -- SPRAYS --
spray.refresh = SPRAYS AKTUALISIEREN
spray.open = ORDNER ÖFFNEN
spray.show = SPRAYS ANDERER SPIELER ANZEIGEN
spray.whitelist = WHITELIST:
spray.blacklist = BLACKLIST: [16][gray](deren Sprays werden nicht angezeigt)

emote.info = Drücke [orange]\[SPACE][], um das Emote zu unterbrechen
emote.roll = [orange]Spieler {0} hat {1} gewählt
emote.0 = Stein
emote.1 = Papier
emote.2 = Schere

menuaccess = \[ DU KANNST EINE LOBBY HOSTEN, WENN DU IN EINER MISSION BIST ]

playerinfo = \[ ES GIBT KEINE VERBÜNDETEN IN DEINEM TEAM ]

skateboard = \ Geschwindigkeit: [#{1}]{0}[][light]U/s \n [16]Drücke \[SHIFT], um nach vorne zu dashen

spect = [b][orange]{2}\n[red]STELLE KERNEL IN RUHEZUSTAND\nFEHLER: KANN RUHEZUSTAND NICHT AKTIVIEREN AUFGRUND\nUNGENÜGEND BLUT\nUNGENÜGEND BLUT\n{3}\n[blue]INFO: DU KANNST ANDEREN ZUSCHAUEN MIT [orange]\[{0}/{1}][]
spect.temp = WARNUNG: DIE EINHEIT IST KURZZEITIG UNVERFÜGBAR
spect.perm = WARNUNG: DIE EINHEIT IST PERMANENT UNVERFÜGBAR
spect.press = SETZE FORT MIT [orange]\[R][] DRÜCKEN ZUM NEUSTARTEN
spect.waves = SETZE FORT MIT WARTEN AUF DIE NÄCHSTE WELLE
spect.round = SETZE FORT MIT WARTEN AUF DIE NÄCHSTE RUNDE
spect.death = SETZE FORT MIT WARTEN AUF DEN TOD

# customization
custom.hats = HÜTE
custom.jackets = JACKEN
custom.cancel = ABBRECHEN
custom.buy = KAUFEN

custom.message = Möchtest du sicher [orange]{1}[] für {0}[orange]P[] kaufen
custom.not-enough-message = [red]Du kannst es dir nicht leisten[]

custom.1 = Fischerhut
custom.2 = Spitzenhaube
custom.3 = Kultistenhut
custom.4 = Kleine Öhrchen
custom.5 = Katzenohren
custom.7 = Jacke
custom.8 = Dienstmädchenkleid
custom.9 = Kultistenmantel

# bindings
keybind.lobby-tab = LOBBY-TAB
keybind.player-list = SPIELERLISTE
keybind.settings = EINSTELLUNGEN
keybind.player-indicators = SPIELER-INDIKATOREN
keybind.player-information = SPIELER-INFORMATIONEN
keybind.point = AUF FADENKREUZ ZEIGEN
keybind.spray = SPRAY
keybind.emote-wheel = EMOTE-RAD
keybind.chat = CHAT ÖFFNEN
keybind.chat-scroll-up = CHAT-VERLAUF NACH OBEN SCROLLEN
keybind.chat-scroll-down = CHAT-VERLAUF NACH UNTEN SCROLLEN
keybind.spectate = ZUSCHAUERMODUS
keybind.spectate-next = NÄCHSTEM SPIELER ZUSCHAUEN
keybind.spectate-prev = VORHERIGEM SPIELER ZUSCHAUEN
