# maintainers:
# xzxADIxzx

# notifications
outdated-mod = 사용 중인 Jaket 버전이 [red]오래되었습니다[]!\n[16][light]{0} ► {1} /// {2}
unprivileged = [red]치트[]를 사용할 수 없습니다!\n[16][light]로비 주인만이 이러한 권한을 부여할 대상을 선택할 수 있습니다
major-assist = [red]어시스트[]를 사용할 수 없습니다!\n[16][light]전투 중인 기계라면 누구도 주요 어시스트를 사용해서는 안 됩니다. 그것은 불공정하기 때문입니다
load-mission = [red]임무을 변경[]할 수 없습니다!\n[16][light]로비 주인만이 변경할 수 있습니다

spray.choose = [red]아직 스프레이 이미지를 선택하지 않았습니다.\n[16][light]분명 설정에서 할 수 있을 겁니다 :I
spray.toobig = [red]이 이미지는 너무 큽니다.\n[16][light]최대 크기는 512KB로 제한되어 있습니다 :o

lobby.copied = [green]로비 코드가 성공적으로 복사되었습니다!\n[16][light]친구들에게 공유해서 함께 플레이해 보세요 :D
lobby.failed = [red]클립보드에서 로비 코드를 찾을 수 없습니다.\n[16][light]공백 등이 없이 올바르게 복사되었는지 확인해 보세요 :(
lobby.banned = [red]그 로비에서 차단당했습니다. 슬프네요.\n[16][light]혹시 말썽을 부렸던 건 아닐까요? :)
lobby.modded = [red]호환되지 않는 모드가 설치되어 있습니다.\n[16][light]모드 목록은 공식 GitHub 저장소에서 확인하고 보완할 수 있습니다

player.joined = [green]{0}님이 참여했습니다!
player.died = [orange]{0}님이 사망하셨습니다.
player.left = [red]{0}님이 떠났습니다.
player.banned = [red]{0}님이 차단되었습니다!

fish.too-small = [red]이 생선을 담기에는 팬이 너무 작습니다 :<
fish.fail = [red]생선 요리에 실패했습니다 :<
bait.took = [green]물고기가 미끼를 물었습니다 :D
bait.nope = [red]이 미끼는 여기서 통하지 않습니다 :<

game.countdown = 새 라운드가 [orange]{0} 초[] 후에 시작합니다...
game.lone-team = [red]활성화된 팀이 하나뿐입니다. 플레이어를 다시 배정한 뒤 미션을 재시작하세요
game.win = [#{1}]{0}[] 팀이 이겼습니다!
team.No0 = 노랑
team.No1 = 빨강
team.No2 = 초록
team.No3 = 파랑
team.No4 = 분홍

# interface
chat.tip = 원하는 메시지를 입력하거나, 잘 모르겠다면 /help를 입력하세요
chat.you = 당신
chat.you-only = 당신이 입력 중 입니다...
chat.others = \ 그리고 다른 사람들
chat.single = \ 님이 입력 중 입니다...
chat.multiple = \ 이 입력 중 입니다...

lobby-tab.lobby = -- 로비 --
lobby-tab.create = 로비 생성
lobby-tab.creating = 생성 중...
lobby-tab.close = 로비 닫기
lobby-tab.leave = 로비 떠나기
lobby-tab.invite = 친구 초대
lobby-tab.codes = -- 연결 --
lobby-tab.copy = 로비 코드 복사
lobby-tab.join = 코드로 참가
lobby-tab.list = 공개 로비 찾기
lobby-tab.config = -- 설정 --
lobby-tab.name = 로비 이름
lobby-tab.private = 비공개
lobby-tab.fr-only = 친구만
lobby-tab.public = 공개
lobby-tab.default = 불명
lobby-tab.allow-pvp = PVP 활성화
lobby-tab.allow-mod = 클라이언트 모드 활성화
lobby-tab.ppp-name = 보스 체력 배율:
lobby-tab.ppp-desc = \n두 번째 플레이어부터 각 플레이어마다 보스의 초기 체력에 추가로 적용되는 비율입니다
lobby-tab.heal-bosses = 사망 시 보스 체력 회복
lobby-tab.gamemode = 게임모드
lobby-tab.cheats = 치트 관리

lobby-list.name = -- 로비 찾기 --
lobby-list.refresh = 새로고침
lobby-list.refreshing = 새로고침 중
lobby-list.search = 찾기

gameconfig.name = -- 게임모드 --
gameconfig.mods = 규칙:
gameconfig.slowmo = \  슬로우 모션
gameconfig.hammer = \  해머 광란
gameconfig.bleedy = \  출혈
gameconfig.titles.No0 = 캠페인
gameconfig.titles.No1 = 맨헌트
gameconfig.titles.No2 = 대전
gameconfig.titles.No3 = 아레나
gameconfig.titles.No4 = 군비 경쟁
gameconfig.titles.No5 = 세상을   \n   칠해라
gameconfig.titles.No6 = 숨바꼭질
gameconfig.titles.No7 = 보스 러쉬
gameconfig.titles.No8 = 하드코어
gameconfig.briefs.No0 = 게임플레이 변경 없이 즐기는 가장 전통적인 Jaket 경험으로, 일반적인 플레이에 기본으로 권장되는 모드입니다.{0}
gameconfig.briefs.No1 = [pink]분홍 팀[]은 미션을 완수해야 하며, 다른 팀들은 그들을 추격해 제거해야 합니다.{0}
gameconfig.briefs.No2 = 승자라는 칭호를 두고 모든 팀이 싸우는 치열한 경쟁입니다. 1대1 대결에 가장 적합합니다.{0}
gameconfig.briefs.No3 = 대전 모드와 유사하지만, 다수의 플레이어가 참여하는 대규모 전투에 최적화된 모드입니다.{0}
gameconfig.briefs.No4 = 매 라운드마다 각 팀에게 무작위 무기가 지급되며, 해당 무기는 적을 처치한 다른 팀이 빼앗을 수 있습니다.{0}
gameconfig.briefs.No5 = 붓을 들고 세상을 팀의 색으로 칠하세요. 가장 넓은 영역을 차지한 팀이 승리합니다.{0}
gameconfig.briefs.No6 = 먹잇감이 포식자가 되었습니다. [pink]분홍 팀[]은 숨어 있는 팀들을 추적하며, 마지막까지 살아남은 팀이 모든 것을 차지합니다.{0}
gameconfig.briefs.No7 = 강화된 보스들과 끝없이 전투를 벌일 수 있는, 놀랍도록 혁신적이고 [i]독창적인[] 게임 모드입니다.{0}
gameconfig.briefs.No8 = 진정한 기계들의 유일한 선택지입니다. 그럴 자격이 있음을 증명하세요.{0}
gameconfig.totals.pvp = \  PvP 강제 활성화\n
gameconfig.totals.hps = \  팀 기반 목숨 제한 리스폰\n
gameconfig.totals.hok = \  적 처치 시 추가 회복\n
gameconfig.totals.nce = \  일반 적 조우 없음\n
gameconfig.totals.wle = \  무작위 적 웨이브 등장\n

privileges.name = -- 권한 --
privileges.lower = 권한 없음:
privileges.upper = 권한 있음:
privileges.warn = 권한을 가진 플레이어는 치트를 사용할 수 있고 다른 이들과 달리 제한도 받지 않습니다. 그러니 로비를 터트릴 가능성이 있고, 실제로 그럴 수도 있으니 조심하세요.

player-list.team = -- 팀 --
player-list.info = 팀은 날개의 색으로 구분됩니다. 이는 주로 대전용이므로, 서로를 공격하고 싶지 않다면 같은 팀에 참가하세요.
player-list.list = -- 플레이어 --
player-list.owner = 로비의 주인입니다. 당신의 목숨은 그 손에 달려 있습니다 :D
player-list.clear = 차단 목록 초기화

settings.general = -- 일반 --
settings.default = 기본
settings.green = 초록
settings.vanilla = 바닐라
settings.chatloc = 채팅 위치
settings.skipmsg = 환영 메시지 스킵
settings.sprays = 스프레이 설정
settings.controls = -- 조작 --
settings.reset = 초기화

spray.name = -- 스프레이 --
spray.refresh = 스프레이 새로고침
spray.open = 폴더 열기
spray.show = 다른 플레이어의 스프레이 표시
spray.whitelist = 화이트리스트:
spray.blacklist = 블랙리스트: [16][gray](이들의 스프레이는 숨겨집니다)

emote.info = [orange]\[SPACE][] 를 눌러 감정표현을 중단하세요
emote.roll = [orange]{0} 님이 {1}를 냈습니다
emote.0 = 바위
emote.1 = 보
emote.2 = 가위

menuaccess = \[ 미션을 불러온 후 로비를 생성할 수 있습니다 ]

playerinfo = \[ 현재 팀에 다른 팀원이 없습니다 ]

skateboard = \ 속력: [#{1}]{0}[][light]U/s \n [16]\[SHIFT] 를 눌러 앞으로 대쉬

spect = [b][orange]{2}\n[red]커널 최대 절전 모드 진입 중\n오류: 다음 사유로 최대 절전 모드 진입 불가\n혈액 부족\n혈액 부족\n{3}\n[blue]정보: [orange]\[{0}/{1}][] 키로 다른 플레이어를 관전할 수 있습니다
spect.temp = 경고: 유닛이 일시적으로 비활성화됨
spect.perm = 경고: 유닛이 영구적으로 비활성화됨
spect.press = [orange]\[R][] 키를 눌러 재시작하십시오
spect.waves = 다음 웨이브까지 대기하십시오
spect.round = 다음 라운드까지 대기하십시오
spect.death = 사망 시까지 대기하십시오

# customization
custom.hats = 모자
custom.jackets = 겉옷
custom.cancel = 취소
custom.buy = 구매

custom.message = {0}[orange]P[]로 [orange]{1}[] 를 구매하시겠습니까?
custom.not-enough-message = [red]포인트가 부족합니다[]

custom.1 = 낚시꾼 모자
custom.2 = 메이드 레이스
custom.3 = 광신도 모자
custom.4 = 작은 귀
custom.5 = 고양이 귀
custom.7 = 재킷
custom.8 = 메이드 드레스
custom.9 = 광신도 코트

# bindings
keybind.lobby-tab = 로비 탭
keybind.player-list = 플레이어 목록
keybind.settings = 설정
keybind.player-indicators = 플레이어 위치
keybind.player-information = 플레이어 정보
keybind.point = 십자선에 핑 찍기
keybind.spray = 스프레이
keybind.emote-wheel = 감정표현
keybind.chat = 채팅 열기
keybind.chat-scroll-up = 기록 위로 이동
keybind.chat-scroll-down = 기록 아래로 이동
keybind.spectate = 관전자 모드
keybind.spectate-next = 다음 플레이어 관전
keybind.spectate-prev = 이전 플레이어 관전
